name: GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.12.0

      - name: Install and Run
        run: |
          npm install
          node src/index.js

      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt

      - name: Github Push
        run: |
          git config --global user.email "qq1092672755@gmail.com"
          git config --global user.name "强子"
          git add .
          git commit -m "自动化提交"
          git push origin master
